# Generated by Django 5.0.6 on 2026-06-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('gym_admin', 'Gym Admin'), ('manager', 'Manager'), ('monitor', 'Monitor'), ('teacher', 'Profesor'), ('student', 'Alumno')], default='student', max_length=20),
        ),
    ]
