# Generated by Django 5.0.6 on 2026-06-19 17:15

import uuid

import django.db.models.functions.text
from django.db import migrations, models


def dedupe_emails_and_backfill_usernames(apps, schema_editor):
    """Hace seguro el AddConstraint contra datos existentes (prod):

    - Backfill de username para filas con username vacío (no debería haber, pero
      el nuevo modelo lo auto-genera y queremos coherencia).
    - Dedupe de (lower(email), organization) duplicados que existieran de antes de
      la unicidad por-org: al duplicado se le sufija el email para no romper el
      AddConstraint. En una BD fresca (seed) esto es no-op.
    """
    CustomUser = apps.get_model('accounts', 'CustomUser')

    for user in CustomUser.objects.filter(models.Q(username__isnull=True) | models.Q(username='')):
        user.username = uuid.uuid4().hex
        user.save(update_fields=['username'])

    seen = set()
    qs = CustomUser.objects.exclude(email='').order_by('pk')
    for user in qs:
        key = (user.email.lower(), user.organization_id)
        if key in seen:
            local, _, domain = user.email.partition('@')
            user.email = f'{local}+dup{user.pk}@{domain}' if domain else f'{user.email}+dup{user.pk}'
            user.save(update_fields=['email'])
        else:
            seen.add(key)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0024_organization_subdomain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RunPython(dedupe_emails_and_backfill_usernames, noop_reverse),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('organization'), condition=models.Q(('organization__isnull', False), models.Q(('email', ''), _negated=True)), name='uniq_email_per_org'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('organization__isnull', True), models.Q(('email', ''), _negated=True)), name='uniq_email_platform'),
        ),
    ]
