# Generated by Django 5.0.6 on 2026-07-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadministrador'), ('gym_admin', 'Administrador'), ('manager', 'Gerente'), ('monitor', 'Monitor'), ('teacher', 'Profesor'), ('student', 'Alumno')], default='student', max_length=20),
        ),
    ]
