# Generated by Django 5.0.6 on 2026-07-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0026_alter_paymentaccount_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(models.F('organization'), models.F('rut'), condition=models.Q(('rut__isnull', False)), name='uniq_rut_per_org'),
        ),
    ]
