# Generated by Codex on 2026-09-01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_student_benefit'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='teacher_payment_cycle_effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='teacher_payment_cycle_previous_start_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ciclo anterior mientras un cambio programado aun no entra en vigencia.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='teacher_payment_cycle_start_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Dia de inicio del ciclo de pago del profesor. 1 = mes calendario.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='teacher_payment_cycle_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='teacher_payment_cycle_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_payment_cycle_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TeacherPaymentCycleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_start_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('new_start_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('effective_from', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('active', 'Activo'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_payment_cycle_changes', to='core.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_payment_cycle_changes_requested', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_payment_cycle_changes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='teacherpaymentcyclechange',
            index=models.Index(fields=['organization', 'teacher', 'effective_from'], name='accounts_te_organiz_b4ed45_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherpaymentcyclechange',
            index=models.Index(fields=['teacher', 'status'], name='accounts_te_teacher_bce813_idx'),
        ),
    ]
