"""Invariantes del rediseño: email único por org + subdominio + username oculto.

- Email puede repetirse entre orgs, pero no dentro de la misma org.
- El subdominio del Host resuelve la organización (404 si no existe).
- El login es por email, acotado al subdominio.
- /api/users/ ya no expone username; la org se crea con subdominio (validado).
"""
import pytest
from django.contrib.auth import get_user_model
from django.db import IntegrityError

User = get_user_model()

pytestmark = pytest.mark.django_db

PASSWORD = 'Passw0rd2026'


# --- Email único por organización -------------------------------------------

def test_same_email_in_two_orgs_is_allowed(make_organization, make_user):
    org_a = make_organization('A')
    org_b = make_organization('B')
    u_a = make_user('juan_a', organization=org_a, role='student', email='juan@demo.local')
    u_b = make_user('juan_b', organization=org_b, role='teacher', email='juan@demo.local')
    assert u_a.email == u_b.email
    assert u_a.organization_id != u_b.organization_id


def test_dup_email_same_org_violates_db_constraint(make_organization, make_user):
    org_a = make_organization('A')
    make_user('first', organization=org_a, email='dup@demo.local')
    with pytest.raises(IntegrityError):
        # Case-insensitive: 'DUP@..' colisiona con 'dup@..' dentro de la misma org.
        make_user('second', organization=org_a, email='DUP@demo.local')


def test_api_create_dup_email_same_org_returns_400(api_client, make_organization, make_user):
    org_a = make_organization('A')
    admin = make_user('admin_a', organization=org_a, role='gym_admin', email='admin@a.local')
    make_user('taken', organization=org_a, role='student', email='taken@a.local')
    api_client.force_authenticate(admin)

    resp = api_client.post(
        '/api/users/',
        {'email': 'taken@a.local', 'role': 'student', 'password': PASSWORD, 'organization': org_a.id},
        format='json',
    )
    assert resp.status_code == 400
    assert 'email' in resp.data


# --- Username oculto ---------------------------------------------------------

def test_users_api_does_not_expose_username(api_client, make_organization, make_user):
    org_a = make_organization('A')
    admin = make_user('admin_a', organization=org_a, role='gym_admin', email='admin@a.local')
    api_client.force_authenticate(admin)

    resp = api_client.get(f'/api/users/{admin.id}/')
    assert resp.status_code == 200
    assert 'username' not in resp.data
    assert resp.data['email'] == 'admin@a.local'


def test_api_created_user_gets_opaque_autogenerated_username(api_client, make_organization, make_user):
    org_a = make_organization('A')
    admin = make_user('admin_a', organization=org_a, role='gym_admin', email='admin@a.local')
    api_client.force_authenticate(admin)

    resp = api_client.post(
        '/api/users/',
        {'email': 'nuevo@a.local', 'role': 'student', 'password': PASSWORD, 'organization': org_a.id},
        format='json',
    )
    assert resp.status_code == 201, resp.data
    created = User.objects.get(email__iexact='nuevo@a.local')
    # username auto-generado, opaco (uuid hex de 32), nunca igual al email.
    assert created.username and created.username != created.email
    assert len(created.username) == 32


# --- Resolución de organización por subdominio ------------------------------

def test_unknown_subdomain_returns_404_on_api(api_client):
    resp = api_client.post(
        '/api/login/', {'email': 'x@x.com', 'password': 'y'}, format='json',
        HTTP_HOST='no-existe.localhost',
    )
    assert resp.status_code == 404


def test_health_is_allowlisted_even_on_unknown_subdomain(api_client):
    resp = api_client.get('/api/health/', HTTP_HOST='no-existe.localhost')
    assert resp.status_code == 200


# --- Login por email + subdominio (aislamiento) -----------------------------

def test_login_by_email_resolves_within_subdomain_org(api_client, make_organization, make_user):
    org_a = make_organization('A')  # subdomain org-1
    org_b = make_organization('B')  # subdomain org-2
    make_user('juan_a', organization=org_a, role='student', email='juan@demo.local', password=PASSWORD)
    make_user('juan_b', organization=org_b, role='teacher', email='juan@demo.local', password=PASSWORD)

    r_a = api_client.post(
        '/api/login/', {'email': 'juan@demo.local', 'password': PASSWORD}, format='json',
        HTTP_HOST=f'{org_a.subdomain}.localhost',
    )
    assert r_a.status_code == 200
    assert r_a.json()['role'] == 'student'
    assert r_a.json()['organization'] == org_a.id

    r_b = api_client.post(
        '/api/login/', {'email': 'juan@demo.local', 'password': PASSWORD}, format='json',
        HTTP_HOST=f'{org_b.subdomain}.localhost',
    )
    assert r_b.status_code == 200
    assert r_b.json()['role'] == 'teacher'
    assert r_b.json()['organization'] == org_b.id


def test_superadmin_login_on_apex(api_client, make_user):
    make_user('root', organization=None, role='superadmin', email='root@platform.local', password=PASSWORD)
    r = api_client.post(
        '/api/login/', {'email': 'root@platform.local', 'password': PASSWORD}, format='json',
        HTTP_HOST='localhost',
    )
    assert r.status_code == 200
    assert r.json()['role'] == 'superadmin'
    assert r.json()['organization'] is None


# --- Creación de organización con subdominio --------------------------------

def test_create_org_requires_subdomain(api_client, make_user):
    su = make_user('root2', organization=None, role='superadmin', email='root2@platform.local')
    api_client.force_authenticate(su)
    resp = api_client.post('/api/organizations/', {'name': 'X', 'slug': 'x-org'}, format='json')
    assert resp.status_code == 400
    assert 'subdomain' in resp.data


def test_create_org_rejects_reserved_subdomain(api_client, make_user):
    su = make_user('root3', organization=None, role='superadmin', email='root3@platform.local')
    api_client.force_authenticate(su)
    resp = api_client.post(
        '/api/organizations/',
        {'name': 'X', 'slug': 'x-org-3', 'subdomain': 'admin'},
        format='json',
    )
    assert resp.status_code == 400
    assert 'subdomain' in resp.data


def test_create_org_with_valid_subdomain_maps(api_client, make_user):
    su = make_user('root4', organization=None, role='superadmin', email='root4@platform.local')
    api_client.force_authenticate(su)
    resp = api_client.post(
        '/api/organizations/',
        {'name': 'New Gym', 'slug': 'new-gym', 'subdomain': 'new-gym'},
        format='json',
    )
    assert resp.status_code == 201, resp.data
    assert resp.data['subdomain'] == 'new-gym'
    # El subdominio recién creado resuelve a la org (login da 400 cred inválidas, no 404).
    r = api_client.post(
        '/api/login/', {'email': 'nadie@new-gym.local', 'password': 'x'}, format='json',
        HTTP_HOST='new-gym.localhost',
    )
    assert r.status_code == 400


# --- Login ESTRICTAMENTE acotado (regresión de los fixes de seguridad) -------
# El login no debe tener fallbacks cross-org ni por username: sólo email dentro del
# contexto del subdominio (o plataforma en el apex). Cubre los agujeros detectados
# en revisión adversarial (escalada tenant→plataforma, cross-org, org-user en apex).

def test_no_login_superadmin_desde_subdominio_de_org(api_client, make_organization, make_user):
    org = make_organization('A')
    make_user('root_platform', organization=None, role='superadmin',
              email='root@platform.local', password=PASSWORD)
    resp = api_client.post(
        '/api/login/', {'email': 'root@platform.local', 'password': PASSWORD},
        format='json', HTTP_HOST=f'{org.subdomain}.localhost',
    )
    assert resp.status_code == 400  # no se puede escalar a plataforma desde un tenant


def test_no_login_cross_org(api_client, make_organization, make_user):
    org_a = make_organization('A')
    org_b = make_organization('B')
    make_user('only_b', organization=org_b, role='gym_admin',
              email='only@b.local', password=PASSWORD)
    resp = api_client.post(
        '/api/login/', {'email': 'only@b.local', 'password': PASSWORD},
        format='json', HTTP_HOST=f'{org_a.subdomain}.localhost',
    )
    assert resp.status_code == 400  # email de ORG B no entra en el subdominio de ORG A


def test_no_login_por_username(api_client, make_organization, make_user):
    org = make_organization('A')
    user = make_user('un_username_humano', organization=org, role='gym_admin',
                     email='humano@a.local', password=PASSWORD)
    # Enviar el username (no el email) NO autentica, ni con el Host correcto.
    resp = api_client.post(
        '/api/login/', {'email': user.username, 'password': PASSWORD},
        format='json', HTTP_HOST=f'{org.subdomain}.localhost',
    )
    assert resp.status_code == 400


def test_org_user_no_entra_en_apex(api_client, make_organization, make_user):
    org = make_organization('A')
    make_user('org_user', organization=org, role='gym_admin',
              email='orguser@a.local', password=PASSWORD)
    # Apex (testserver = plataforma): sólo cuentas organization NULL.
    resp = api_client.post(
        '/api/login/', {'email': 'orguser@a.local', 'password': PASSWORD}, format='json',
    )
    assert resp.status_code == 400
