# Generated by Django 5.0.6 on 2026-04-16 02:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_refactor_classes_and_enrollments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-marked_at', 'id']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='gym_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.gymclass'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente')], default='absent', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='closure_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('completed_early', 'Completada anticipadamente')], default='scheduled', max_length=20),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student_marked',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher_validated',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='validation_notes',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('gym_class', 'student')},
        ),
    ]
