# Generated by Django 5.0.6 on 2026-04-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_holiday_holiday_unique_holiday_scope_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='source_type',
            field=models.CharField(choices=[('system', 'Sistema'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
