# Generated by Django 5.0.6 on 2026-04-17 13:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_plan_studentplan_consumptionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherpaymentrecord',
            options={'ordering': ['-calculated_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='teacherpaymentrule',
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.RemoveField(
            model_name='teacherpaymentrule',
            name='rule_type',
        ),
        migrations.RemoveField(
            model_name='teacherpaymentrule',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='teacherpaymentrule',
            name='valid_until',
        ),
        migrations.RemoveField(
            model_name='teacherpaymentrule',
            name='value',
        ),
        migrations.AddField(
            model_name='teacherpaymentrecord',
            name='calculated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacherpaymentrecord',
            name='class_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_payment_records', to='core.gymclass'),
        ),
        migrations.AddField(
            model_name='teacherpaymentrecord',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='core.teacherpaymentrule'),
        ),
        migrations.AddField(
            model_name='teacherpaymentrule',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='teacherpaymentrule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_rules', to='core.branch'),
        ),
        migrations.AddField(
            model_name='teacherpaymentrule',
            name='calculation_base',
            field=models.CharField(blank=True, choices=[('attendance', 'Asistencia'), ('enrollment', 'Inscripcion')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherpaymentrule',
            name='class_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_rules', to='core.classtype'),
        ),
        migrations.AddField(
            model_name='teacherpaymentrule',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_rules', to='core.discipline'),
        ),
        migrations.AddField(
            model_name='teacherpaymentrule',
            name='payment_type',
            field=models.CharField(choices=[('fixed_per_class', 'Fijo por clase'), ('per_student', 'Por alumno presente'), ('revenue_share', 'Porcentaje de ingreso')], default='fixed_per_class', max_length=30),
        ),
        migrations.AlterField(
            model_name='teacherpaymentrecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherpaymentrecord',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='teacherpaymentrule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teacherpaymentrecord',
            unique_together={('teacher', 'class_instance')},
        ),
        migrations.RemoveField(
            model_name='teacherpaymentrecord',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='teacherpaymentrecord',
            name='period_label',
        ),
        migrations.RemoveField(
            model_name='teacherpaymentrecord',
            name='total_classes',
        ),
    ]
