# Generated by Django 5.0.6 on 2026-04-17 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_teacher_assignments(apps, schema_editor):
    TeacherPaymentRule = apps.get_model('core', 'TeacherPaymentRule')
    through_model = TeacherPaymentRule.teachers.through
    rows = []
    for rule in TeacherPaymentRule.objects.exclude(teacher_id__isnull=True).only('id', 'teacher_id'):
        rows.append(through_model(teacherpaymentrule_id=rule.id, customuser_id=rule.teacher_id))
    if rows:
        through_model.objects.bulk_create(rows, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_teacherpaymentrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherpaymentrule',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='assigned_payment_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherpaymentrule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_teacher_assignments, noop_reverse),
    ]
