# Generated by Django 5.2.1 on 2026-05-29 14:37

import django.utils.timezone
from django.db import migrations, models


def copy_marked_at_to_checked_at(apps, schema_editor):
    Attendance = apps.get_model('core', 'Attendance')
    for attendance in Attendance.objects.all().only('id', 'marked_at'):
        attendance.checked_at = attendance.marked_at
        attendance.source = 'manual'
        attendance.save(update_fields=['checked_at', 'source'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_teacherpaymentrule_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('qr', 'QR'), ('system', 'Sistema')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('late', 'Tarde'), ('excused', 'Justificado'), ('no_show', 'No asistió')], default='absent', max_length=10),
        ),
        migrations.RunPython(copy_marked_at_to_checked_at, migrations.RunPython.noop),
    ]
