# Generated by Django 5.0.6 on 2026-06-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_public_invite_and_trial_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('completed_early', 'Completada anticipadamente')], default='scheduled', max_length=20),
        ),
    ]
