# Generated by Django 5.0.6 on 2026-06-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_gymclass_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherpaymentrule',
            name='payment_type',
            field=models.CharField(choices=[('fixed_per_class', 'Fijo por clase'), ('per_student', 'Por alumno presente'), ('per_enrolled', 'Por alumno inscrito'), ('per_hour', 'Por hora'), ('revenue_share', 'Porcentaje de ingreso'), ('monthly_fixed', 'Sueldo mensual fijo')], default='fixed_per_class', max_length=30),
        ),
    ]
