# Generated by Django 5.0.6 on 2026-06-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_discipline_classtype_description_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='unlimited_classes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentplan',
            name='unlimited_classes',
            field=models.BooleanField(default=False),
        ),
    ]
