# Generated by Django 5.0.6 on 2026-06-15 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_plan_unlimited_classes_studentplan_unlimited_classes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='trial_followup_sent_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se envió el email de seguimiento de la clase de prueba.', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Esta inscripción se generó mediante una clase de prueba.'),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='reactivation_expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='suspend_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentplan',
            name='enrollment_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Matrícula individual del alumno para este plan (0 = sin matrícula).', max_digits=10),
        ),
        migrations.AddField(
            model_name='studentplan',
            name='enrollment_fee_due_at',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento de la matrícula. Por defecto un año desde la creación.', null=True),
        ),
        migrations.AddField(
            model_name='studentplan',
            name='enrollment_fee_paid_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo pagó la matrícula. Vacío = pendiente.', null=True),
        ),
        migrations.AddField(
            model_name='teacherpaymentrule',
            name='per_plan_price_base',
            field=models.CharField(choices=[('active_enrollments', 'Todos los alumnos inscritos'), ('present_attendees', 'Solo alumnos presentes')], default='active_enrollments', help_text='Solo para per_plan_price: ¿sobre quién se calcula el porcentaje?', max_length=20),
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('completed_early', 'Completada anticipadamente'), ('suspended', 'Suspendida')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherpaymentrule',
            name='payment_type',
            field=models.CharField(choices=[('fixed_per_class', 'Fijo por clase'), ('per_student', 'Por alumno presente'), ('per_enrolled', 'Por alumno inscrito'), ('per_hour', 'Por hora'), ('revenue_share', 'Porcentaje de ingreso'), ('monthly_fixed', 'Sueldo mensual fijo'), ('per_plan_price', 'Porcentaje del precio del plan del alumno')], default='fixed_per_class', max_length=30),
        ),
        migrations.CreateModel(
            name='TrialFollowupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='¿Enviar emails de seguimiento de clases de prueba?')),
                ('minutes_after_class_end', models.PositiveIntegerField(default=30, help_text='Minutos tras el fin de la clase para enviar el email.')),
                ('email_subject', models.CharField(default='¿Qué te pareció tu clase en {org_name}?', max_length=200)),
                ('email_body', models.TextField(default='Hola {student_name},\n\nGracias por venir a tu clase de prueba de {class_name} en {org_name}. ¡Esperamos que la hayas disfrutado!\n\nSi quieres seguir entrenando con nosotros, inscríbete aquí: {signup_link}\n\n¡Te esperamos!\n— Equipo {org_name}')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial_followup_config', to='core.organization')),
            ],
            options={
                'verbose_name': 'Configuración de email de prueba',
                'verbose_name_plural': 'Configuraciones de email de prueba',
            },
        ),
    ]
