# Generated by Django 5.0.6 on 2026-06-19 17:15

import re

import core.models
from django.db import migrations, models


RESERVED = {'admin', 'app', 'www', 'api', 'qa', 'static', 'media', 'localhost', 'mail'}


def _slug_to_subdomain(slug):
    """Deriva un subdominio válido (^[a-z0-9-]+, sin reservados) desde un slug."""
    value = re.sub(r'[^a-z0-9-]+', '-', (slug or '').lower()).strip('-')
    if not value or value in RESERVED:
        value = f'org-{value}' if value else 'org'
    return value[:50]


def populate_subdomains(apps, schema_editor):
    """Backfill defensivo para datos existentes (prod). En una BD fresca es no-op:
    el seed asigna el subdominio explícitamente."""
    Organization = apps.get_model('core', 'Organization')
    used = set(
        Organization.objects.exclude(subdomain__isnull=True).values_list('subdomain', flat=True)
    )
    for org in Organization.objects.filter(subdomain__isnull=True):
        base = _slug_to_subdomain(org.slug)
        candidate = base
        suffix = 2
        while candidate in used:
            candidate = f'{base}-{suffix}'[:50]
            suffix += 1
        org.subdomain = candidate
        org.save(update_fields=['subdomain'])
        used.add(candidate)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_attendance_trial_followup_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subdomain',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[core.models.validate_subdomain]),
        ),
        migrations.RunPython(populate_subdomains, noop_reverse),
    ]
