# Generated by Django 5.0.6 on 2026-07-06 03:14

import core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_organization_subdomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='mercadopago', max_length=30)),
                ('provider_preference_id', models.CharField(blank=True, max_length=64, null=True)),
                ('provider_payment_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_process', 'in_process'), ('approved', 'approved'), ('rejected', 'rejected'), ('cancelled', 'cancelled'), ('refunded', 'refunded')], default='pending', max_length=20)),
                ('status_detail', models.CharField(blank=True, max_length=120, null=True)),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('plan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('enrollment_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_provider_payload', models.JSONField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='core.organization')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='core.plan')),
                ('student_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_transactions', to='core.studentplan')),
                ('target_student_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_fee_transactions', to='core.studentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='mercadopago', max_length=30)),
                ('provider_payment_id', models.CharField(blank=True, max_length=64, null=True)),
                ('raw_body', models.TextField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('processed_ok', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='core.paymenttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='mercadopago', max_length=30)),
                ('provider_user_id', models.CharField(max_length=64)),
                ('access_token', core.fields.EncryptedTextField()),
                ('refresh_token', core.fields.EncryptedTextField()),
                ('public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', models.CharField(blank=True, max_length=255, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('connected', 'Conectada'), ('disconnected', 'Desconectada')], default='connected', max_length=20)),
                ('is_sandbox', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='core.organization')),
            ],
            options={
                'unique_together': {('organization', 'provider')},
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['organization', 'status'], name='core_paymen_organiz_e2dbff_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', 'status'], name='core_paymen_user_id_f199cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payment_id__isnull', False)), fields=('provider', 'provider_payment_id'), name='uniq_provider_payment'),
        ),
    ]
