# Generated by Django 5.0.6 on 2026-07-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_paymenttransaction_webhookevent_paymentaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='scope',
            field=models.TextField(blank=True, null=True),
        ),
    ]
