# Generated by Django 5.0.6 on 2026-07-23 15:49

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_paymentaccount_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='access_token',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='refresh_token',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
