# Generated by Django 5.0.6 on 2026-07-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_paymentaccount_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='trial_validity_days',
            field=models.PositiveIntegerField(default=7, help_text='Días hacia adelante en que se puede agendar una clase de prueba.'),
        ),
    ]
