# Generated by Django 5.0.6 on 2026-08-02 02:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_expiry_notification_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto cobrado. Debe ser mayor a cero.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reference', models.CharField(blank=True, default='', help_text='Nº de transferencia, folio o nota. Vacío si fue efectivo sin comprobante.', max_length=120)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_payments', to='core.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('student_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payments', to='core.studentplan')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='manualpayment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='manual_payment_amount_positive'),
        ),
    ]
