# Generated by Django 5.0.6 on 2026-08-02 23:36

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F, OuterRef, Subquery


def backfill_enrollment_student_plan(apps, schema_editor):
    """Deriva `Enrollment.student_plan` del `ConsumptionLog` que la respalda (#9).

    Best-effort: espeja `get_enrollment_student_plan` de `core/services/reservations.py`
    —mismo match (`user`/`class_instance`) y mismo orden de desempate
    (`-consumed_at, -id`)—, así que el resultado del backfill es el mismo que ya
    calculaba en caliente el reverso de consumo. Un solo `UPDATE` con `Subquery`
    correlacionada por fila (no un loop en Python) para que corra igual de rápido en
    SQLite que en Postgres.

    El match además exige que el `student_plan` del log sea de la MISMA organización
    que la clase que consumió —comparado contra `class_instance__organization_id` del
    propio log, no con un `OuterRef` a `gym_class__organization_id`: un `UPDATE` no
    admite joins en la tabla que se está actualizando, así que la comparación de
    organización tiene que resolverse enteramente DENTRO de la subquery (`class_instance`
    ahí ya es, por construcción, la misma clase del enrollment, vía el match de
    `class_instance_id=OuterRef('gym_class_id')`)—. Logs de antes del fix de scoping
    multitenant pueden apuntar a un `student_plan` de OTRA organización (mismo
    `user`/`class_instance` por coincidencia, plan ajeno); sin esta restricción el
    backfill copiaría esa referencia cross-tenant al FK. No hay forma de reparar ese
    dato retroactivamente, así que se descarta como si no hubiera log.

    Las reservas sin `ConsumptionLog` que matchee —trial, sin plan, cross-org, o
    anteriores a que existiera el log— quedan en NULL a propósito: no hay de dónde
    inferir el plan y inventar uno sería peor que dejarlo vacío.
    """
    Enrollment = apps.get_model('core', 'Enrollment')
    ConsumptionLog = apps.get_model('core', 'ConsumptionLog')

    latest_log_for_enrollment = ConsumptionLog.objects.filter(
        user_id=OuterRef('student_id'),
        class_instance_id=OuterRef('gym_class_id'),
        student_plan__organization_id=F('class_instance__organization_id'),
    ).order_by('-consumed_at', '-id')

    Enrollment.objects.update(
        student_plan_id=Subquery(latest_log_for_enrollment.values('student_plan_id')[:1])
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_manualpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='core.studentplan'),
        ),
        # Reverse = noop: el AddField se revierte solo al desaplicar (DROP COLUMN), y no
        # hay nada que deshacer del lado de los datos —la migración anterior a esta no
        # tenía la columna, así que no hay estado previo que restaurar—.
        migrations.RunPython(backfill_enrollment_student_plan, migrations.RunPython.noop),
    ]
