# Generated by Django 5.0.6 on 2026-08-03 04:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_enrollment_student_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('late', 'Tarde'), ('excused', 'Justificado'), ('no_show', 'No asistió')], max_length=10)),
                ('new_status', models.CharField(choices=[('present', 'Presente'), ('absent', 'Ausente'), ('late', 'Tarde'), ('excused', 'Justificado'), ('no_show', 'No asistió')], max_length=10)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='core.attendance')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_changes_recorded', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_change_logs', to='core.organization')),
            ],
            options={
                'ordering': ['-changed_at', 'id'],
            },
        ),
    ]
