# Generated by Django 5.0.6 on 2026-08-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_attendancechangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancechangelog',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('qr', 'QR'), ('system', 'Sistema')], default='manual', max_length=10),
        ),
    ]
