# Generated by Django 5.0.6 on 2026-08-03

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def _is_usable_student_plan(student_plan, on_date):
    """Espejo de la mitad de `describe_student_plan` (core/services/plans.py) que hace
    falta para decidir "usable" == `PlanStatus.ACTIVE`. Replicada INLINE y no importada:
    los modelos históricos de una migración de datos (`apps.get_model`) no tienen
    managers ni métodos custom (`valid_on`, `is_usable`), así que ni `StudentPlanQuerySet.
    valid_on` ni `describe_student_plan` están disponibles acá — hay que traducir el
    predicado a Python plano.

    Mismo orden de precedencia que la fuente (fechas antes que `is_active`): vencida o
    por iniciar es EXPIRED/UPCOMING sin mirar el flag; dentro de la ventana, `is_active`
    manda; y agotada (saldo consumido sin ser ilimitada) tampoco es usable. El eje de
    pago (`payment_status`/matrícula) no participa de "usable" en la fuente, así que
    tampoco se replica acá.
    """
    if student_plan.end_date and student_plan.end_date < on_date:
        return False
    if student_plan.start_date and student_plan.start_date > on_date:
        return False
    if not student_plan.is_active:
        return False
    if not student_plan.unlimited_classes and (student_plan.classes_used or 0) >= (student_plan.total_classes or 0):
        return False
    return True


def backfill_recurring_enrollment_student_plan(apps, schema_editor):
    """Puebla `RecurringEnrollment.student_plan` (10.x) SOLO cuando el alumno tiene
    EXACTAMENTE UN candidato posible — mismos criterios org-scopeados que
    `resolve_student_plan_for_reservation` (core/services/reservations.py:59-120): planes
    del alumno (`user_id`) intersectados con la organización DE LA SUSCRIPCIÓN
    (`class_template.organization_id`, no `student.organization_id`), vigentes hoy y
    usables (ver `_is_usable_student_plan`).

    La organización la manda `class_template.organization_id` y no `student.
    organization_id` a propósito — el mismo motivo que documenta la memoria del
    proyecto sobre FKs propias sin organización: `RecurringEnrollment.student` es CASCADE
    sobre el usuario, no sobre el tenant, así que un alumno movido de organización DESPUÉS
    de crear la recurrencia conservaría la fila apuntando a la organización vieja
    (la de la plantilla), no a la nueva. Intersectar por ahí, y no por `student.
    organization_id`, es lo que impide que el backfill le cuelgue a esa fila un plan de
    la organización NUEVA del alumno (cross-tenant).

    0 candidatos (sin plan usable) o 2+ (ambigüedad, el alumno tiene más de una
    membresía vigente) dejan la FK en NULL a propósito: no hay de dónde inferir uno solo
    de forma defendible. Esas filas siguen con el comportamiento actual —el loop de
    recurrencia re-resuelve el plan por instancia, sin imputación fija— hasta que el
    alumno vuelva a suscribirse eligiendo plan explícitamente.

    Las series YA TERMINADAS (`end_date` seteado y anterior a hoy) se saltan aunque tengan
    un único candidato: no van a materializar ninguna instancia más, así que la FK no
    cambiaría ninguna imputación futura y sí dejaría un `RESTRICT` colgado sobre una
    membresía que el gimnasio podría querer quitar (`remove_membership` pasa a exigir que
    se borre la recurrencia primero). El corte es la FECHA y no `is_active`: una serie
    PAUSADA sin `end_date` vencido es reactivable desde la UI del alumno y sí se
    backfillea.

    Iterado en Python (no un `UPDATE`+`Subquery` como 0033): a diferencia del backfill de
    `Enrollment.student_plan`, "usable" acá depende de saldo consumido/ilimitado además
    de fechas, un predicado que no se puede expresar completo en un `filter()` sin
    duplicar `describe_student_plan`. El volumen de filas (recurrencias de un SaaS de
    gimnasios) es chico, así que iterar no es un problema de performance.
    """
    RecurringEnrollment = apps.get_model('core', 'RecurringEnrollment')
    StudentPlan = apps.get_model('core', 'StudentPlan')

    today = timezone.localdate()

    for recurring in RecurringEnrollment.objects.select_related('class_template').all():
        if recurring.end_date and recurring.end_date < today:
            continue
        organization_id = recurring.class_template.organization_id
        candidates = [
            sp
            for sp in StudentPlan.objects.filter(
                user_id=recurring.student_id,
                organization_id=organization_id,
            )
            if _is_usable_student_plan(sp, today)
        ]

        resolved_id = candidates[0].id if len(candidates) == 1 else None
        if recurring.student_plan_id != resolved_id:
            RecurringEnrollment.objects.filter(pk=recurring.pk).update(student_plan_id=resolved_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_attendancechangelog_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringenrollment',
            name='student_plan',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='recurring_enrollments',
                to='core.studentplan',
            ),
        ),
        # Reverse = noop: el AddField se revierte solo al desaplicar (DROP COLUMN), y no
        # hay estado previo que restaurar del lado de los datos (misma convención que
        # 0033 para el backfill hermano de `Enrollment.student_plan`).
        migrations.RunPython(backfill_recurring_enrollment_student_plan, migrations.RunPython.noop),
    ]
