# Generated by Django 5.0.6 on 2026-08-03 20:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_recurringenrollment_student_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.CharField(help_text='Concepto cobrado (ej. "pesas", "toalla").', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del concepto. Debe ser mayor a cero.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_line_items_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_line_items', to='core.organization')),
                ('student_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_line_items', to='core.studentplan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='chargelineitem',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='charge_line_item_amount_positive'),
        ),
    ]
