# Generated by Django 5.0.6 on 2026-08-04 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_chargelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='class_generation_window_days',
            field=models.PositiveIntegerField(default=21, help_text='Días hacia adelante en que se materializan clases de series recurrentes.', validators=[django.core.validators.MaxValueValidator(366)]),
        ),
    ]
