# Generated by Django 5.0.6 on 2026-08-04 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_organization_class_generation_window_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='class_pruning_grace_days',
            field=models.PositiveIntegerField(default=7, help_text='Días de gracia antes de podar una clase terminada sin inscripciones ni historia.', validators=[django.core.validators.MaxValueValidator(90)]),
        ),
    ]
