# Generated by Django 5.0.6 on 2026-08-06 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_class_occupancy_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='free_class_teacher_payment_value',
            field=models.FloatField(default=0, help_text='Valor de UNA clase de un plan gratuito, para el pago al profesor. 0 = sin configurar (bloquea la creación de planes gratuitos).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
