# Generated by Django 5.0.6 on 2026-08-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_free_class_teacher_payment_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtemplate',
            name='has_substitute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classtemplate',
            name='substitute_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='has_substitute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='substitute_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
