# Generated by Django 5.0.6 on 2026-08-07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_classtemplate_has_substitute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='max_reservation_window_days',
            field=models.IntegerField(
                default=21,
                help_text='Días hacia adelante en que se puede reservar una clase.',
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(366),
                ],
            ),
        ),
    ]
