# Generated by Codex on 2026-08-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0050_alter_manualpayment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtemplate',
            name='substitute_teacher',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='substitute_class_templates',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='classtemplate',
            name='substitution_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classtemplate',
            name='substitution_assigned_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_template_substitutions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='classtemplate',
            name='substitution_source',
            field=models.CharField(
                blank=True,
                choices=[
                    ('external_admin', 'Externo asignado por admin'),
                    ('admin_assigned', 'Profesor asignado por admin'),
                    ('teacher_claimed', 'Tomada por profesor'),
                ],
                default='',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='substitute_teacher',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='substituted_classes',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='substitution_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='substitution_assigned_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_class_substitutions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='substitution_source',
            field=models.CharField(
                blank=True,
                choices=[
                    ('external_admin', 'Externo asignado por admin'),
                    ('admin_assigned', 'Profesor asignado por admin'),
                    ('teacher_claimed', 'Tomada por profesor'),
                ],
                default='',
                max_length=30,
            ),
        ),
    ]
