# Generated by Codex on 2026-09-01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_enrollment_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPaymentCalculationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('mode', models.CharField(choices=[('missing', 'Calcular faltantes'), ('recalculate_pending', 'Recalcular pendientes')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('voided', 'Anulado')], default='active', max_length=20)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('classes_count', models.PositiveIntegerField(default=0)),
                ('records_created_count', models.PositiveIntegerField(default=0)),
                ('records_updated_count', models.PositiveIntegerField(default=0)),
                ('records_voided_count', models.PositiveIntegerField(default=0)),
                ('skipped_paid_teachers_count', models.PositiveIntegerField(default=0)),
                ('skipped_existing_count', models.PositiveIntegerField(default=0)),
                ('skipped_no_rule_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_payment_calculation_batches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_payment_calculation_batches', to='core.organization')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_teacher_payment_calculation_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='teacherpaymentrecord',
            name='calculation_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='core.teacherpaymentcalculationbatch'),
        ),
        migrations.AddField(
            model_name='teacherpaymentrecord',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherpaymentrecord',
            name='void_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teacherpaymentrecord',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherpaymentrecord',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_teacher_payment_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teacherpaymentrecord',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='teacherpaymentrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_voided', False)), fields=('teacher', 'class_instance'), name='uniq_active_teacher_payment_record_per_class'),
        ),
        migrations.AddIndex(
            model_name='teacherpaymentcalculationbatch',
            index=models.Index(fields=['organization', 'period_start', 'period_end'], name='core_teache_organiz_1885f2_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherpaymentcalculationbatch',
            index=models.Index(fields=['organization', 'status'], name='core_teache_organiz_009059_idx'),
        ),
    ]
