# Generated by Codex on 2026-09-01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_teacher_payment_calculation_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='student_inactivity_grace_days',
            field=models.PositiveIntegerField(
                default=3,
                help_text='Días desde el vencimiento del último plan para considerar inactivo a un alumno.',
                validators=[django.core.validators.MaxValueValidator(366)],
            ),
        ),
    ]
