# Generated by Django 5.2.6 on 2026-09-20 21:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_gymclass_reactivation_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='consultation_duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('pack', 'Pack'), ('single_class', 'Clase suelta'), ('trial', 'Trial'), ('giftcard', 'Giftcard'), ('personalized', 'Clases personalizadas'), ('consultation', 'Consulta individual')], max_length=20),
        ),
        migrations.CreateModel(
            name='IndividualConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('expected_duration_minutes', models.PositiveIntegerField(default=60)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('actual_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('scheduled', 'Acordada'), ('started', 'Iniciada'), ('finished', 'Finalizada'), ('expired', 'Vencida'), ('cancelled', 'Anulada')], default='available', max_length=20)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_individual_consultations', to=settings.AUTH_USER_MODEL)),
                ('finished_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_individual_consultations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_consultations', to='core.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_consultations', to='core.plan')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_individual_consultations', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_individual_consultations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationDateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('new_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_date_changes', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreed_date_changes', to='core.individualconsultation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='individualconsultation',
            index=models.Index(fields=['organization', 'professional', 'status'], name='core_indivi_organiz_59e32e_idx'),
        ),
        migrations.AddIndex(
            model_name='individualconsultation',
            index=models.Index(fields=['organization', 'student', 'status'], name='core_indivi_organiz_a56813_idx'),
        ),
        migrations.AddIndex(
            model_name='individualconsultation',
            index=models.Index(fields=['organization', 'status', 'expires_at'], name='core_indivi_organiz_b13a3b_idx'),
        ),
    ]
