# Generated by Django 5.2.6 on 2026-09-20 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_individual_consultations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='individualconsultation',
            name='payment_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='individual_consultation', to='core.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='plan',
            name='consultation_professional',
            field=models.ForeignKey(blank=True, help_text='Profesional que presta este producto de consulta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
