# Generated by Django 5.2.6 on 2026-09-21 01:00

from datetime import date

from django.conf import settings
from django.db import migrations, models


def backfill_payout_ranges(apps, schema_editor):
    TeacherPayout = apps.get_model('core', 'TeacherPayout')
    for payout in TeacherPayout.objects.filter(period_start__isnull=True):
        start = date(payout.period_year, payout.period_month, 1)
        end = date(payout.period_year + (payout.period_month == 12), (payout.period_month % 12) + 1, 1)
        payout.period_start = start
        payout.period_end = end.fromordinal(end.toordinal() - 1)
        payout.save(update_fields=['period_start', 'period_end'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_consultation_purchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherpayout',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teacherpayout',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherpayout',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_payout_ranges, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='teacherpayout',
            constraint=models.UniqueConstraint(fields=('teacher', 'organization', 'period_start', 'period_end'), name='uniq_teacher_payout_exact_range'),
        ),
    ]
